# jlpm in JupyterLab 4 is yarn 3, and this is a yarn 2+ compatible configuration
# file.
#
# Config reference: https://yarnpkg.com/configuration/yarnrc
#
nodeLinker: node-modules
httpTimeout: 300000
npmRegistryServer: "https://registry.npmjs.org/"
